region: ap-south-1

function_name: qxf2-docker-stats
handler: service.handler
description: My first lambda function
runtime: python3.7
timeout: 60
environment_variables:
    env_1: foo
    env_2: baz
    
build:
  source_directories: lib # a comma delimited list of directories in your project root that contains source to package.
