name: daily-pto-deploy
on:
  push:
    branches:
      - daily_pto
    paths:
      - 'daily_pto/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy code to Lambda
      uses: qxf2/py-lambda-action@v1.0.2
      with:
        lambda_directory: 'daily_pto'
        lambda_function_name: 'arn:aws:lambda:ap-south-1:285993504765:function:daily_pto'
        lambda_layer_arn: 'arn:aws:lambda:ap-south-1:285993504765:layer:daily_pto'
        requirements_txt: 'daily_pto/requirements.txt'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.SKYPE_SENDER_REGION }}
