name: deploy-skype-sender
on:
  push:
    branches:
      - master
    paths:
      - 'skype_sender/**'
      - 'tests/test_integration_skype_lambda.py'
      - 'tests/test_end_to_end_employee_skype_message.py'
      - 'tests/helpers/**'
      - 'tests/conf/**'
      - '.github/workflows/skype_sender.yml'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.TEST_SKYPE_SENDER_REGION }}
      # Execute Test for skype sender lambda
      - name: Run test for skype lambda
        run : python -m pytest tests/test_integration_skype_lambda.py -sv
      # Execute end to end test
      - name: Run end to end test
        run: python -m pytest tests/test_end_to_end_employee_skype_message.py -sv
  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Deploy code to Lambda
      uses: qxf2/py-lambda-action@v1.0.2
      with:
        lambda_directory: 'skype_sender'
        lambda_function_name: ${{ secrets.SKYPE_SENDER_FUNCTION }}
        lambda_layer_arn: 'arn:aws:lambda:ap-south-1:285993504765:layer:skpy'
        requirements_txt: 'skype_sender/requirements.txt'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.SKYPE_SENDER_REGION }}